### PR TITLE
add december event

### PR DESCRIPTION
**Pull request by lucaferranti**
TODO:

- [x] decide room location @FabsOliveira did we agree on a room already?
- [ ]  update registration link

### CODE REVIEW

**Review by FabsOliveira — COMMENTED** [review]
I had an idea: how about I give an initial short talk based on this: https://github.com/Datseris/whyjulia-manifesto and other sources? So the programme could be: me for 15 min on "why Julia is awesome" and then you with a 30 min demo. How does that sound?

I booked Otakkari 1, U9 (U271), hoping more people would come!

**Comment by lucaferranti** [comment]
> I had an idea: how about I give an initial short talk based on this: https://github.com/Datseris/whyjulia-manifesto and other sources? So the programme could be: me for 15 min on "why Julia is awesome" and then you with a 30 min demo. How does that sound?
> 
> I booked Otakkari 1, U9 (U271), hoping more people would come!

That's a great idea! (I'm giving on Wednesday a talk + workshop about Julia in Eindhoven university, so can recycle some material from there)

Last thing to sort out when we start advertising, last time we discussed we could have a longer event with pizza or similar afterwards, should we do this?

**Comment by FabsOliveira** [comment]
> Last thing to sort out when we start advertising, last time we discussed we could have a longer event with pizza or similar afterwards, should we do this?

I could not get pizza, but at least I got some holiday-themed sweets and glogi. I booked the from 15.45 to 17.30 but I can adjust if needed. I will however advertise with the Guild of Physics promising sweets and overall patches!

**Comment by lucaferranti** [comment]
for the patches we need to make sure Jaakko is coming, he had printed those

**Comment by FabsOliveira** [comment]
> for the patches we need to make sure Jaakko is coming, he had printed those

Indeed. Maybe we can contact him directly? 
Update: we will have glögi/coffee/tea, Christmas tarts and gingerbread!  ☃️

**Pull request merged**
